export const APP_STORAGE_PREFIX = "ornitho2ebird";
export const LANGUAGE_COOKIE_NAME = `${APP_STORAGE_PREFIX}_language`;

export const UI_LANGUAGES = [
  { value: "en", label: "English" },
  { value: "fr", label: "Francais" },
  { value: "ca", label: "Catala" },
  { value: "de", label: "Deutsch" },
];

export const EBIRD_LANGUAGES = [
  { value: "en", label: "English" },
  { value: "af", label: "Afrikaans" },
  { value: "sq", label: "Albanian" },
  { value: "ar", label: "Arabic" },
  { value: "hy", label: "Armenian" },
  { value: "as", label: "Assamese" },
  { value: "ast", label: "Asturian" },
  { value: "az", label: "Azerbaijani" },
  { value: "eu", label: "Basque" },
  { value: "bn", label: "Bangla" },
  { value: "bn_IN", label: "Bengali, India" },
  { value: "bn_BD", label: "Bangla, Bangladesh" },
  { value: "bg", label: "Bulgarian" },
  { value: "ca", label: "Catalan" },
  { value: "zh", label: "Chinese, Mandarin (traditional)" },
  { value: "zh_HK", label: "Chinese, Mandarin (traditional), Hong Kong" },
  { value: "zh_SIM", label: "Chinese, Simple" },
  { value: "ht_HT", label: "Creole, Haiti" },
  { value: "hr", label: "Croatian" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "nl", label: "Dutch" },
  { value: "en_AVI", label: "English, AviList" },
  { value: "en_AU", label: "English, Australia" },
  { value: "en_BD", label: "English, Bangladesh" },
  { value: "en_HAW", label: "English, Hawaii" },
  { value: "en_HBW", label: "English, HBW" },
  { value: "en_HK", label: "English, Hong Kong" },
  { value: "en_IN", label: "English, India" },
  { value: "en_IOC", label: "English, IOC" },
  { value: "en_KE", label: "English, Kenya" },
  { value: "en_MY", label: "English, Malaysia" },
  { value: "en_NZ", label: "English, New Zealand" },
  { value: "en_PH", label: "English, Philippines" },
  { value: "en_UK", label: "English, United Kingdom" },
  { value: "en_US", label: "English, United States" },
  { value: "en_ZA", label: "English, South Africa" },
  { value: "en_AE", label: "English, UAE" },
  { value: "et", label: "Estonian" },
  { value: "fo", label: "Faroese" },
  { value: "fi", label: "Finnish" },
  { value: "fr", label: "French" },
  { value: "fr_AOU", label: "French, AOU" },
  { value: "fr_CA", label: "French, Canada" },
  { value: "fr_FR", label: "French, France" },
  { value: "fr_GF", label: "French, French Guiana" },
  { value: "fr_GP", label: "French, Guadeloupe" },
  { value: "fr_HT", label: "French, Haiti" },
  { value: "gl", label: "Gallegan" },
  { value: "ka", label: "Georgian" },
  { value: "de", label: "German" },
  { value: "el", label: "Greek" },
  { value: "gu", label: "Gujarati" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "hu", label: "Hungarian" },
  { value: "is", label: "Icelandic" },
  { value: "id", label: "Indonesian" },
  { value: "it", label: "Italian" },
  { value: "ja", label: "Japanese" },
  { value: "ks_IN", label: "Kashmiri (India)" },
  { value: "kk", label: "Kazakh" },
  { value: "kn", label: "Kannada" },
  { value: "kok", label: "Konkani" },
  { value: "ko", label: "Korean" },
  { value: "ky", label: "Kyrgyz" },
  { value: "lbj", label: "Ladakhi" },
  { value: "lv", label: "Latvian" },
  { value: "lt", label: "Lithuanian" },
  { value: "ml", label: "Malayalam" },
  { value: "mi", label: "Maori" },
  { value: "mni", label: "Manipuri" },
  { value: "mr", label: "Marathi" },
  { value: "lus", label: "Mizo" },
  { value: "mn", label: "Mongolian" },
  { value: "ne_IN", label: "Nepali, India" },
  { value: "ne_NP", label: "Nepali, Nepal" },
  { value: "no", label: "Norwegian" },
  { value: "or", label: "Odia" },
  { value: "fa", label: "Persian" },
  { value: "pl", label: "Polish" },
  { value: "pt_AO", label: "Portuguese, Angola" },
  { value: "pt_RAA", label: "Portuguese, Azores" },
  { value: "pt_BR", label: "Portuguese, Brazil" },
  { value: "pt_RAM", label: "Portuguese, Madeira" },
  { value: "pt_PT", label: "Portuguese, Portugal" },
  { value: "pa", label: "Punjabi" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "sr", label: "Serbian" },
  { value: "sk", label: "Slovak" },
  { value: "sl", label: "Slovenian" },
  { value: "es", label: "Spanish" },
  { value: "es_AR", label: "Spanish, Argentina" },
  { value: "es_CL", label: "Spanish, Chile" },
  { value: "es_CR", label: "Spanish, Costa Rica" },
  { value: "es_CU", label: "Spanish, Cuba" },
  { value: "es_DO", label: "Spanish, Dominican Republic" },
  { value: "es_EC", label: "Spanish, Ecuador" },
  { value: "es_HN", label: "Spanish, Honduras" },
  { value: "es_MX", label: "Spanish, Mexico" },
  { value: "es_PA", label: "Spanish, Panama" },
  { value: "es_PE", label: "Spanish, Peru" },
  { value: "es_PR", label: "Spanish, Puerto Rico" },
  { value: "es_PY", label: "Spanish, Paraguay" },
  { value: "es_ES", label: "Spanish, Spain" },
  { value: "es_UY", label: "Spanish, Uruguay" },
  { value: "es_VE", label: "Spanish, Venezuela" },
  { value: "sv", label: "Swedish" },
  { value: "ta_IN", label: "Tamil (India)" },
  { value: "te", label: "Telugu" },
  { value: "th", label: "Thai" },
  { value: "tr", label: "Turkish" },
  { value: "uk", label: "Ukrainian" },
  { value: "zu", label: "Zulu" },
];

export const DEFAULT_WEBSITE_BY_LANGUAGE = {
  en: "ornitho network",
  fr: "faune-france.org",
  ca: "ornitho.cat",
  de: "ornitho.de",
};

export const DEFAULT_SPECIES_COMMENT_TEMPLATE = {
  short:
    '${ s.count_precision }${ s.count } ind. ${ s.time ? " - " + s.time : "" } - <a href="https://www.ornitho.ch/index.php?m_id=54&id=${ s.id }">ornitho</a>${ s.comment ? " - " + s.comment : "" }',
  long:
    '${ s.count_precision }${ s.count } - <a href="https://www.ornitho.ch/index.php?m_id=54&id=${ s.id }">${ s.time }</a>${ s.comment ? " - " + s.comment : "" }',
  limit: 5,
};

export const DEFAULT_SETTINGS = {
  uiLanguage: "en",
  ebirdLanguage: "en",
  autoAssignDuration: 24,
  autoAssignDistance: 3,
  defaultNumberObserver: 1,
  customizedSpeciesComments: true,
  speciesCommentTemplate: DEFAULT_SPECIES_COMMENT_TEMPLATE,
  advancedEnabled: false,
  mapboxToken: "",
  githubToken: "",
  globalStaticMap: {
    show: false,
    style: "satellite-v9",
    pathStyle: {
      strokeWidth: 5,
      strokeColor: "#AD8533",
      strokeOpacity: 1,
    },
    markerStyle: {
      markerSize: "small",
      markerSymbol: "circle",
      markerColor: "#808080",
    },
  },
  websiteName: "",
};
